name: Sync SWA roles with GitHub repo permissions
description: >
  swa-github-role-sync syncs Azure Static Web Apps and GitHub roles by posting invitation links to Discussions.
author: Atsushi Nakamura
# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: users
  color: purple

inputs:
  github-token:
    description: 'GitHub token with permissions to read collaborators and create
      discussions.'
    required: true

  target-repo:
    description:
      'Target repository in owner/repo format. Defaults to the current
      repository.'
    required: false

  swa-name:
    description: 'Name of the target Azure Static Web App.'
    required: true

  swa-resource-group:
    description: 'Resource group name of the Static Web App.'
    required: true

  swa-domain:
    description:
      'Domain of the Static Web App (e.g. your-app.azurestaticapps.net). Used
      for invite links.'
    required: false

  invitation-expiration-hours:
    description: 'Invitation link expiration in hours (1-168).'
    required: false
    default: '168'

  role-for-admin:
    description: 'SWA role name assigned to GitHub admin users.'
    required: false
    default: github-admin

  role-for-write:
    description: 'SWA role name assigned to GitHub write/maintain users.'
    required: false
    default: github-writer

  role-prefix:
    description: 'Prefix used to detect SWA roles managed by this action.'
    required: false
    default: github-

  discussion-category-name:
    description: 'Discussion category name where invite summary Discussion will be created.'
    required: true

  discussion-title-template:
    description: 'Template for discussion title. Placeholders: {swaName}, {repo}, {date}, {login}.'
    required: false
    default: SWA access invite for @{login} ({swaName}) - {date}

  discussion-body-template:
    description: |
      Template for discussion body. Placeholders: {swaName}, {repo}, {summaryMarkdown}, {login}, {role}, {inviteUrl}, {invitationExpirationHours}.
    required: false
    default: |
      Hi @{login},

      You now have **{role}** access to **{swaName}** from **{repo}**.

      - Invite link: {inviteUrl}
      - Role: {role}
      - Expires in: {invitationExpirationHours} hours

      Use the invite link above to authenticate. After you confirm access, close this discussion so the admins know you're done. If the invite expired, comment here and we'll re-run the sync.

runs:
  using: node20
  main: dist/sync.js

outputs:
  added-count:
    description: Number of users newly invited on SWA.
  updated-count:
    description: Number of users whose SWA roles were updated.
  removed-count:
    description: Number of users removed from SWA roles.
  discussion-url:
    description: URL of the first created Discussion (kept for backward compatibility).
  discussion-urls:
    description: Newline-separated URLs of every invite Discussion (empty when no invites).
